title: Peladen Blog
email: medullium@yandex.com
description: >- # this means to ignore newlines until "baseurl:"
  semua tentang jaringan komputer
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.peladen.web.id"

show_excerpts: true
paginate: 10
paginate_path: "/page/:num/"

twitter_username: v0latile
github_username:  bwk65535

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/