version: "3"
services:
  jekyll:
    build:
      context: ../.
      dockerfile: docker/dev.Dockerfile
    entrypoint: bash -c "bundle install && bundle exec jekyll serve --host=0.0.0.0 --livereload --drafts --trace"
    # entrypoint: cat
    image: v0latile/jekyll:latest
    ports:
      - "4000:4000"
      - "35729:35729"
    # tty: true
    volumes:
      - $PWD:/srv/jekyll
      - jekyll-bundle:/usr/local/bundle
      - jekyll-gems:/home/jekyll/gems

volumes:
  jekyll-bundle:
  jekyll-gems: