version: "3.8"
services:
  jekyll:
    build:
      context: ../.
      dockerfile: docker/Dockerfile
    image: v0latile/peladen:latest
    networks:
      - peladen-net
    ports:
      - "8080:80"

networks:
  peladen-net: