version: "3.8"
services:
  jekyll:
    entrypoint: bundle exec jekyll serve --trace --drafts
    # entrypoint: cat
    image: jekyll/jekyll:latest
    network_mode: "host"
    volumes:
      - $PWD:/app
      - jekyll-bundle:/usr/local/bundle
      - jekyll-gems:/usr/gem
      # - $PWD/vendor/bundle:/usr/local/bundle
      # - $PWD/vendor/gems:/usr/gem
    # tty: true
    user: jekyll
    working_dir: /app

volumes:
  jekyll-bundle:
  jekyll-gems: